### PR TITLE
Update to 0.4.0-pre

### PR DESCRIPTION
**Pull request by samnm**
Depends on https://github.com/Jengamon/wren-sys/pull/1

I am still very new to Rust so please let me know if I messed up.

### CODE REVIEW

**Comment by Jengamon** [comment]
Once the wren-sys PR is merged, could you bump a commit here? Travis seems to not like to build unless there is an actual new commit happening.

**Comment by samnm** [comment]
Will do 👍

**Comment by Jengamon** [comment]
If you still have interest in this, I'm now open to updating to 0.4.0 now that it's been officially released.

**Comment by Jengamon** [comment]
Updated to 0.4.0

**Pull request closed without merging**
